### ISSUE TITLE
Validation doctest failing to build with 8.2.0

### ISSUE THREAD

**Issue by eborden** [qfpl/validation#12]
Looks like some changes in base made `Control.Applicative` redundant. Either doctest drops `-Wall` or we pull out the dreaded `CPP`

```
{-# LANGUAGE CPP #-}
module Main where

import Build_doctests (deps)
#if __GLASGOW_HASKELL__ < 802
import Control.Applicative
#endif
import Control.Monad
```

**Comment by eborden** [comment]
Stackage ticket here: https://github.com/fpco/stackage/issues/2949

**Comment by gwils** [comment]
@eborden I reckon this is fixed now. https://travis-ci.org/qfpl/validation/jobs/286354986
Do you agree?

**Comment by eborden** [comment]
Yeah, looks good to me. I was able to build and test with hackage nightly from validation `HEAD`.

**Comment by gwils** [comment]
Sweet! I'll close the issue.
