### ISSUE TITLE
Remove Validation data type

### ISSUE THREAD

**Issue by tonymorris** [qfpl/validation#3]
The `Validation` data type was originally motivated by the absence of an instance of `Traversable` for `Either`, however, this is now remedied since `base-4.7.0.0` (08 April 2014).

Therefore, it is proposed to remove the `Validation` data type and then rename `AccValidation` to `Validation`.

**Comment by phadej** [comment]
Should `ValidationT` be removed as well, (there is `ExceptT`) ?

**Comment by flip111** [comment]
Would be nice to have a transformer for what now is `AccValidation`

**Comment by phadej** [comment]
`Applicative`s compose nicely with `Compose` (there is `(Applicative f, Applicative g) => Applicative (Compose f g)` instance), and `Compose` have much more instances than a inlined type would have.
